name: psy_balance
description: PsyBalance MVP
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.1
  supabase_flutter: ^2.10.3
  google_fonts: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.5.5
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

